const assert = require('node:assert/strict');
const { readFile, readdir } = require('node:fs/promises');
const path = require('node:path');
const { describe, it } = require('node:test');

const projectRoot = path.resolve(__dirname, '..');
const tauriDirectory = path.join(projectRoot, 'src-tauri');
const capabilityDirectory = path.join(tauriDirectory, 'capabilities');
const permissionDirectory = path.join(
  tauriDirectory,
  'permissions',
  'autogenerated',
);

const companionCommandPermissions = [
  'allow-activate-reminder-events',
  'allow-activate-pomodoro-events',
  'allow-start-pomodoro',
  'allow-custom-pomodoro-panel-closed',
  'allow-create-reminder',
  'allow-update-reminder',
  'allow-delete-reminder',
  'allow-get-reminder',
  'allow-list-reminders',
  'allow-mark-reminder-completed',
  'allow-get-cursor-position',
  'allow-get-runtime-settings',
  'allow-get-companion-window-position',
  'allow-move-companion-window',
  'allow-set-companion-content-height',
  'allow-show-companion-context-menu',
  'allow-stream-cursor-positions',
  'allow-stop-cursor-positions',
  'allow-update-user-name',
  'allow-update-sticky-message',
];
const preferencesCommandPermissions = [
  'allow-get-preferences-settings',
  'allow-update-preferences-settings',
  'allow-get-credential-status',
  'allow-save-credential',
  'allow-delete-credential',
];
const registeredCommandPermissions = [
  ...companionCommandPermissions,
  ...preferencesCommandPermissions,
];
const eventPermissions = [
  'core:event:allow-listen',
  'core:event:allow-unlisten',
];

const readJson = async (target) =>
  JSON.parse(await readFile(target, 'utf8'));

const readCapability = (role) =>
  readJson(path.join(capabilityDirectory, `${role}.json`));

describe('Tauri IPC authorization', () => {
  it('loads only the two exact local renderer capabilities', async () => {
    const configuration = await readJson(
      path.join(tauriDirectory, 'tauri.conf.json'),
    );
    const capabilityFiles = (await readdir(capabilityDirectory))
      .filter((entry) => entry.endsWith('.json'))
      .sort();

    assert.deepEqual(capabilityFiles, [
      'companion.json',
      'preferences.json',
    ]);
    assert.deepEqual(
      [...configuration.app.security.capabilities].sort(),
      ['companion', 'preferences'],
    );

    for (const role of ['companion', 'preferences']) {
      const capability = await readCapability(role);

      assert.equal(capability.local, true);
      assert.equal(Object.hasOwn(capability, 'remote'), false);
      assert.equal(Object.hasOwn(capability, 'windows'), false);
      assert.deepEqual(capability.webviews, [role]);
      assert.equal(
        capability.webviews.some((label) => label.includes('*')),
        false,
      );
    }
  });

  it('grants completed commands only to their exact renderer role', async () => {
    const companion = await readCapability('companion');
    const preferences = await readCapability('preferences');

    assert.deepEqual(companion.permissions, [
      ...companionCommandPermissions,
      ...eventPermissions,
    ]);
    assert.deepEqual(preferences.permissions, [
      ...preferencesCommandPermissions,
      ...eventPermissions,
    ]);

    for (const permission of companionCommandPermissions) {
      assert.equal(companion.permissions.includes(permission), true);
      assert.equal(preferences.permissions.includes(permission), false);
    }
    for (const permission of preferencesCommandPermissions) {
      assert.equal(preferences.permissions.includes(permission), true);
      assert.equal(companion.permissions.includes(permission), false);
    }
  });

  it('does not grant broad, remote, or renderer-side mutation authority', async () => {
    const forbiddenPermissions = new Set([
      'core:default',
      'core:event:default',
      'core:event:allow-emit',
      'core:event:allow-emit-to',
    ]);
    const forbiddenPrefixes = [
      'fs:',
      'http:',
      'shell:',
      'process:',
      'clipboard:',
      'global-shortcut:',
      'menu:',
      'notification:',
      'tray:',
    ];

    for (const role of ['companion', 'preferences']) {
      const capability = await readCapability(role);

      for (const permission of capability.permissions) {
        assert.equal(forbiddenPermissions.has(permission), false);
        assert.equal(
          forbiddenPrefixes.some((prefix) =>
            permission.startsWith(prefix),
          ),
          false,
        );
      }
    }
  });

  it('generates one narrow allow/deny permission pair per command', async () => {
    const permissionFiles = (await readdir(permissionDirectory))
      .filter((entry) => entry.endsWith('.toml'))
      .sort();

    assert.deepEqual(
      permissionFiles,
      registeredCommandPermissions
        .map(
          (permission) =>
            `${permission.slice('allow-'.length).replaceAll('-', '_')}.toml`,
        )
        .sort(),
    );

    for (const permission of registeredCommandPermissions) {
      const commandName = permission
        .slice('allow-'.length)
        .replaceAll('-', '_');
      const contents = await readFile(
        path.join(permissionDirectory, `${commandName}.toml`),
        'utf8',
      );

      assert.match(contents, new RegExp(`identifier = "${permission}"`));
      assert.match(
        contents,
        new RegExp(
          `identifier = "deny-${permission.slice('allow-'.length)}"`,
        ),
      );
      assert.match(
        contents,
        new RegExp(`commands.allow = \\["${commandName}"\\]`),
      );
      assert.match(
        contents,
        new RegExp(`commands.deny = \\["${commandName}"\\]`),
      );
    }
  });
});
